# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a1cd01244ffe984b9d3dce01090740fbea35cb0cb12d71edf7b7436602c6ded0302028a78405d8ad15b086c7618f5a9dcf498737d5eaa34123c5e533db1cc54

test:
  secret_key_base: 995de46aea0a9330f0856c778952b7b87b05ab8d60054231e0d9ebde5151b2d6899c9b082e9195d5c54dd4d8e1544ee668d0f0ee60f8a1919dc5cdb79277429a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
